Story05
alem-platform/bootcamp-js pull request #17
Opened 2024-10-31 10:56 UTC by aidana-bk

2024-11-05 13:05 UTC, Adilyam requested changes

2024-11-05 13:05 UTC, Adilyam commented on story05/has-own-it/README.md
> +### Prototype Inheritance – Own vs Inherited Properties
```suggestion

```

2024-11-05 13:05 UTC, Adilyam commented on story05/pre-set-this/README.md
> +[this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)
```suggestion
```

2024-11-05 13:05 UTC, Adilyam commented on story05/pre-set-this/README.md
> +
Expected function

2024-11-05 13:05 UTC, Adilyam commented on story05/whats-your-name/README.md
> +[this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)
```suggestion
```

2024-11-05 13:05 UTC, Adilyam commented on story05/whats-your-name/README.md
> +Define a function that takes an object with a `name` property, name it `showYourName`. The function should add a method `showName` to the object that logs the name property using the `this` keyword.
это та же задача как с getValue?

2024-11-07 04:50 UTC, aidana-bk commented on story05/call-constructor/README.md
> +const myDog = new Dog("Rex"); // Output: Dog { type: 'Dog', name: 'Rex' }
Можно, Диас как раз сказал что мы можем переписать в тесте console.log, и как раз будем проверять

2024-11-07 04:56 UTC, aidana-bk commented on story05/whats-your-name/README.md
> +Define a function that takes an object with a `name` property, name it `showYourName`. The function should add a method `showName` to the object that logs the name property using the `this` keyword.
Да, они похожи, но тут на этой неделе тема была this

2024-11-07 10:29 UTC, Adilyam requested changes

2024-11-07 10:29 UTC, Adilyam commented on story05/pre-set-this/README.md
> +Given a function that logs `this`. Use `bind` to create two new functions `showForObj1` and `showForObj2` that set `this` to two differennt given objects.
```suggestion
Given a function that logs `this`. Use `bind` to create two new functions `showForObj1` and `showForObj2` that set `this` to two different given objects.
```

2024-11-07 10:29 UTC, Adilyam commented on story05/pre-set-this/README.md
> +  console.log(this.value);
что тут должно вывести?

2024-11-07 10:29 UTC, Adilyam commented on story05/partial-application/README.md
> +
```
const multiplyByFive = (num) => {
    let bind = this.bind
    return num * 5
}
```

2024-11-07 10:29 UTC, Adilyam commented on story05/pre-set-this/README.md
> +showForObj1(); // Output: A
как это связано с preSetThis?

2024-11-07 10:29 UTC, Adilyam commented on story05/method-swapping/README.md
> +You're given two objects, each with a method that uses this. Swap their methods and verify if they log the correct values after the swap.
функцию не надо писать?
и нужно указать что объекты будут называться именно obj1, obj2

2024-11-07 10:29 UTC, Adilyam commented on story05/inheritance-wizzard/README.md
> +
expected function

2024-11-07 10:29 UTC, Adilyam commented on story05/hybrid-creature/README.md
> +
expected function

2024-11-07 12:49 UTC, Adilyam requested changes

2024-11-07 12:49 UTC, Adilyam commented on story05/math-chain-builder/README.md
> +Implement a system that extends the `Math` object with a new methods:
```suggestion
Extend `Math` object with a new methods:
```

2024-11-07 12:49 UTC, Adilyam commented on story05/math-chain-builder/README.md
> +- `log_a_b`: calculates the logarithm of a base b
```suggestion
- `log`: calculates the logarithm of a base b
```

2024-11-07 12:49 UTC, Adilyam commented on story05/math-chain-builder/README.md
> +- Handle invalid inputs
```suggestion
```

2024-11-07 12:49 UTC, Adilyam commented on story05/inheritance-wizzard/README.md
> +Write a function named `setPrototypeLink` that explicitly sets the **proto** property of an object to link it to another object. This will enable the first object to inherit properties and methods fr
```suggestion
Write a function called `setPrototypeLink` to set the proto property of one object to link it to another, allowing it to inherit properties and methods.
```

2024-11-07 12:49 UTC, Adilyam commented on story05/hybrid-creature/README.md
> +Write a function named `createHybridObject` that accepts an object and a method to add to the prototype of the object. The factory function should return the instance of the object that has been crea
```suggestion
Write a function called `createHybridObject` that takes an object and a method to add to its prototype. The function should return the created object instance.
```

2024-11-07 12:49 UTC, Adilyam commented on story05/call-string/README.md
> +In your file, implement the following functions:
```suggestion
Implement the following functions:
```

2024-11-07 12:49 UTC, Adilyam commented on story05/apply-to-math/README.md
> +
```suggestion
### Instructions 
```

2024-11-07 12:49 UTC, Adilyam commented on story05/apply-to-math/README.md
> +Write functions that creates a mathematical utilities with the following capabilities:
```suggestion
Write functions to create a math utility with these features:
```

2024-11-07 12:49 UTC, Adilyam commented on story05/apply-to-math/README.md
> +2. Chain multiple `Math` operations in sequence
```suggestion
2. Apply multiple `Math` operations in sequence
```

2024-11-07 12:56 UTC, Adilyam approved these changes

2024-11-07 12:56 UTC, merged