story03
alem-platform/bootcamp-js pull request #4
Opened 2024-10-22 12:10 UTC by aidana-bk

2024-10-31 06:47 UTC, Adilyam requested changes

2024-10-31 06:47 UTC, Adilyam commented on story03/math-trio/README.md
> +Write three separate functions that each take two arguments, a and b, and perform basic arithmetic operations without using the corresponding operator.
```suggestion
Implement functions:
```

2024-10-31 06:47 UTC, Adilyam commented on story03/math-trio/README.md
> +
```suggestion
Get ready to create three functions that handle multiplication, division, and modulo, but with a twist — you can’t use \*, /, or %.
```

2024-10-31 06:47 UTC, Adilyam commented on story03/slice-array/README.md
> +  2. size: An integer that specifies the number of elements each sub-array should contain.
```suggestion
Write a function called `sliceArray` that divides the original array into sub-arrays, each having a length equal to the provided size.
If the array cannot be split evenly, the last sub-array should contain the remaining elements.

### Expected Function: 
```
```
```

что если size < 0?

2024-10-31 06:47 UTC, Adilyam commented on story03/value-protector/README.md
> +
```suggestion
Write a function called `scopeGuardian` that manages a value using two inner functions: `increase` to modify the value and `reveal` to access it.

- The outer function `scopeGuardian` should initialize a value to 100.
- It should return two inner functions:
  1. `increase(amount)`: Increases value by the given amount.
  2. `reveal()`: Returns the current value.
  
- `value` should not be accessible outside the scope of `scopeGuardian`.
```

2024-10-31 06:47 UTC, Adilyam commented on story03/value-protector/README.md
> +guard.revealValue(); // Output: 150
```suggestion
guard.revealValue(); // Output: 150
```

непонятно почему 150

2024-10-31 07:03 UTC, aidana-bk commented on story03/slice-array/README.md
> +  2. size: An integer that specifies the number of elements each sub-array should contain.
Студент должен проверять такой кейс, size должен быть >0 (но до этого мне кажется они сами должны догадаться, странно будет прям все расписывать)

2024-10-31 07:07 UTC, aidana-bk commented on story03/value-protector/README.md
> +guard.revealValue(); // Output: 150
Потому что изначальное значение 100, там отсчет с 100 идет

2024-10-31 07:37 UTC, Adilyam requested changes

2024-10-31 07:37 UTC, Adilyam commented on story03/slice-array/README.md
> +in case of invalid input values, function should return initial array
```suggestion
In case of invalid input values, function should return initial array
```

2024-10-31 07:37 UTC, Adilyam commented on story03/round-cut/README.md
> +   This function should round the given number to the nearest integer. Numbers ending in .5 or higher are rounded up, while others are rounded down.
```suggestion
1.`round` - this function should round the given number to the nearest integer. Numbers ending in .5 or higher are rounded up, while others are rounded down.
```

2024-10-31 07:37 UTC, Adilyam commented on story03/round-cut/README.md
> +
Expected functions:

2024-10-31 11:36 UTC, Adilyam requested changes

2024-10-31 11:36 UTC, Adilyam commented on story03/round-cut/README.md
> +Write four separate functions that mimic the behavior of JavaScript's `Math.round()`, `Math.ceil()`, `Math.floor()`, and `Math.trunc()`. You are not allowed to use any built-in Math functions for thi
```suggestion
Write four separate functions that matches the JavaScript's `Math.round()`, `Math.ceil()`, `Math.floor()`, and `Math.trunc()` behavior. You are not allowed to use any built-in Math functions.
```

2024-10-31 11:36 UTC, Adilyam commented on story03/round-cut/README.md
> +
```suggestion
```

2024-10-31 11:36 UTC, Adilyam commented on story03/mirror-issue/README.md
> +- In `mirrorIssue`, declare a local variable named `hero` that shadows the global one.
```suggestion
- In `mirrorIssue`, declare a local variable named `hero`
```

2024-10-31 11:36 UTC, Adilyam commented on story03/mirror-issue/README.md
> +- Modify the local `hero` variable, changing "global" to "local", and return it.
```suggestion
- Modify the local `hero` variable, by replacing the text "global" with "local" and return the modified value.
```

2024-10-31 11:36 UTC, Adilyam commented on story03/mirror-issue/README.md
> +Write a function called `mirrorIssue` where a local variable with the same name as a global variable, `hero`, shadows the global one. Inside `mirrorIssue`, the local `hero` should replace the text "g
```suggestion
Write a function called `mirrorIssue` where a local variable with the same name as a global variable, `hero`, shadows the global one. Inside `mirrorIssue`, the local `hero` should replace the text "global" with "local" and return the modified value, showing the "power struggle" between the global and local scopes.
```

2024-10-31 11:36 UTC, Adilyam commented on story03/mirror-issue/README.md
> +};
```suggestion
var hero = "...";
var mirrorIssue = function () {
  var hero;
  // ...
  return hero;
};
```

2024-10-31 11:36 UTC, Adilyam commented on story03/coercion-conundrum/README.md
> +# Coercion Conundrum
```suggestion
# Smart Conversion
```

2024-10-31 11:36 UTC, Adilyam commented on story03/closure-manipulator/README.md
> +function closureManipulator() {
придумать use case

2024-11-01 05:39 UTC, Adilyam approved these changes

2024-11-01 05:47 UTC, merged